@startuml

hide circle


package " Capa de presentación " as Presentation {
    hide members
    class AuthController
    class DevelopersController
    class JugadorController
    class PartidaController
    class PartidaJugadorController
    class UserRestController
    class CurrentUserRestController
}

package " Capa de lógica de negocio " as BusinessLogic {
    hide members
    class AuthService
    class UserDetailsImplService
    class ManoService
    class JugadorService
    class PartidaService
    class PartidaJugadorService
    class AuthoritiesService
    class UserService
}

package " Capa de recursos " as Resources {
    hide attributes
    interface JugadorRepository {
        Boolean existsById(int id)
        Optional<Jugador> findByUserId(Integer userId)
        List<Jugador> findAll()
        Optional<Jugador> findById(Integer id)
        List<JugadorDTO> findAmigosByUserId(Integer id)
        JugadorDTO findJugadorByUserName(String userName)
    }
    interface PartidaRepository {
        List<Partida> findAllPartidasActivas()
        Optional<Partida> findPartidaByCodigo(String codigo)
    }
    interface PartidaJugadorRepository {
        PartidaJugador findPartidaJugadorbyId(Integer id)
        Integer findNumJugadoresPartida(Integer partidaId)
    }
    interface AuthoritiesRepository {
        Optional<Authorities> findByName(String authority)
    }
    interface UserRepository {
        Optional<User> findByUsername(String username)
        Boolean existsByUsername(String username)
        Optional<User> findById(Integer id)
        Iterable<User> findAllByAuthority(String auth)
    }
}

AuthController ..> UserService
AuthController ..> AuthService
JugadorController ..> JugadorService
PartidaController ..> PartidaService
PartidaController ..> PartidaJugadorService
PartidaJugadorController ..> PartidaJugadorService
PartidaJugadorController ..> PartidaService
CurrentUserRestController ..> UserService
CurrentUserRestController ..> JugadorService
UserRestController ..> UserService
UserRestController ..> AuthoritiesService

AuthService ..> AuthoritiesService
AuthService ..> UserService
AuthService ..> JugadorService
PartidaService ..> ManoService

UserDetailsImplService ..> UserRepository
JugadorService ..> JugadorRepository
PartidaService ..> PartidaRepository
PartidaJugadorService ..> PartidaJugadorRepository
PartidaJugadorService ..> JugadorRepository
AuthoritiesService ..> AuthoritiesRepository
UserService ..> UserRepository


@enduml

