package es.us.dp1.lx_xy_24_25.truco_beasts.mano;

public enum Cantos {
    TRUCO, RETRUCO, VALECUATRO, ENVIDO, REAL_ENVIDO, FALTA_ENVIDO, FLOR, CONTRAFLOR, CONTRAFLOR_AL_RESTO, QUIERO, NO_QUIERO, SUBIR, LISTA_ENVIDOS
}
