package es.us.dp1.lx_xy_24_25.truco_beasts.mano;

public enum Cantos {
    TRUCO, RETRUCO, VALECUATRO, ENVIDO, REAL_ENVIDO, FALTA_ENVIDO, FLOR, CONTRAFLOR, CON_FLOR_ME_ACHICO, QUIERO, NO_QUIERO, SUBIR, LISTA_ENVIDOS, ENVIDO2,LISTA_ENVIDOS_FLOR
}
